### ISSUE TITLE
-v 挂载数据

### ISSUE THREAD

**Issue by chunecai** [qieangel2013/ngx-fastdfs#1]
你的这个能将存储文件数据等信息保存到docker容器外面吗？
还是一定要在docker里面？

**Comment by qieangel2013** [comment]
可以 -v映射出来就可以

**Comment by chunecai** [comment]
我有点蒙，其实我是想让上传保存的文件存放到主机具体的目录下，不要存放在容器的目录底下。
-v 貌似不行。

**Comment by qieangel2013** [comment]
可以

**Comment by chunecai** [comment]
我使用 docker run --net=host --name myfastdfs -idt -p 10080:10080 -v /opt/data/fastdfs:/etc/fastdfs fastdfs:dev '/etc/rc.local'    
使用你的测试命令上传文件，没有上传到我设定的主机目录 /opt/data/fastdfs 底下。

**Comment by chunecai** [comment]
但是我在浏览器上面访问是可以访问到文件的，只是文件没有在挂载的/opt/data/fastdfs 底下；
@qieangel2013

**Comment by qieangel2013** [comment]
你的挂载有问题吧

**Comment by qieangel2013** [comment]
docker run --net=host --name myfastdfs -idt -p 10080:10080 -v /opt/data/fastdfs:/etc/fastdfs fastdfs:dev '/bin/bash'

**Comment by qieangel2013** [comment]
然后自己启动fastdfs，/usr/bin/fdfs_trackerd /etc/fdfs/tracker.conf
 	/usr/bin/fdfs_storaged /etc/fdfs/storage.conf

**Comment by chunecai** [comment]
还是不行。
我现在在想，是不是-v 只是将主机的目录文件映射存放到docker的容器中，但是容器中保存的数据不能放到主机中。

**Comment by chunecai** [comment]
还是在容器里面：
主机里面：
[root@izwz9i9pykkmpsvsnxaqg3z fastdfs]# pwd
/opt/data/fastdfs
[root@izwz9i9pykkmpsvsnxaqg3z fastdfs]# ls
容器里面：
[root@izwz9i9pykkmpsvsnxaqg3z cb9cd9c722bbb11eaadf99952b7f337f0ce0372a9a9fe326ee84b11cb076862a]# docker exec -it myfastdfs /bin/bash
[root@izwz9i9pykkmpsvsnxaqg3z /]# find / -name fwAAAVkS2zOANilrAAA9YA0iXDI170.log
/usr/local/fastDFS/storage/data/00/00/fwAAAVkS2zOANilrAAA9YA0iXDI170.log
[root@izwz9i9pykkmpsvsnxaqg3z /]#

**Comment by qieangel2013** [comment]
映射外部路劲里也应该有图片

**Comment by chunecai** [comment]
我重新删除掉，重新build换个目录先试下

**Comment by chunecai** [comment]
挣扎了一下，还是不行。 还是容器里面有，主机没有。

**Comment by chunecai** [comment]
@qieangel2013  你的 -p 怎么也不管用，默认都是80 端口，修改不了啊。 我修改了 nginx里面的监听的端口，也没有。

**Comment by qieangel2013** [comment]
建议你看一下docker的使用
